### ISSUE TITLE
The firmware-util.sh script not working.

### ISSUE THREAD

**Issue by cparman5** [MrChromebox/website#2]
The firmware-util.sh script not working. I ran the command "cd; curl https://mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh" in the chronos user shell. The menu did not appear, all that appeared was the contents of the firmware-util.sh script. I don't believe this is the behavior that is expected. I'm I doing something wrong here? Thank you in advance for your help.

**Comment by MrChromebox** [comment]
well, you omitted part of the curl command, so the script file didn't download.

https://docs.mrchromebox.tech/docs/fwscript.html

**Comment by cparman5** [comment]
Made the adjustment to command string and the script works fine, Thank you.
