### ISSUE TITLE
Asus Google Meet kit (EXCELSIOR) WP screw method could use a note

### ISSUE THREAD

**Issue by gui710** [MrChromebox/website#26]
Hey! I recently bought an Excelsior chromebox and was a bit confused when I noticed the WP screw method said to remove a screw that didn't exist in the first place. 
I ended up temporarily removing the Wi-Fi card and re-using the screw on the spot marked in the [image](https://docs.mrchromebox.tech/images/wp/Excelsior_wp.jpg) linked in the compatibility list.
Just wanted to let you know since it could be handy for other people!
![image](https://github.com/user-attachments/assets/7a5749e0-1f7a-43cb-8292-e06eec314595)

**Comment by gui710** [comment]
Exactly, apparently this model doesn't have a WP screw by default. 
Using the Wi-Fi screw on that pad/hole acted as a "jumper", shorted the pads and disabled WP.

No screw = WP Enabled
Add screw = WP disabled

**Comment by MrChromebox** [comment]
updated the pic with a note, thanks

**Comment by gui710** [comment]
Thanks for the update!
I just want to mention that not every screw on the unit fits the screw hole (too tight). 
From what I've tried only the Wi-Fi card and NVME screws fit the screw hole.
